### ISSUE TITLE
Angular expressions in strings (interpolation)

### ISSUE THREAD

**Issue by adammathias** [jvandemo/angular-growl-notifications#15]
Any chance that this lib will support interpolation?

That would allow us to Growl strings like "Message sent to {{ email }}".

(Similar to issue https://github.com/JanStevens/angular-growl-2/issues/42)

**Comment by jvandemo** [comment]
Hi @adammathias, interpolation is already supported.

See http://jvandemo.github.io/angular-growl-notifications/ if you want to read more about it:

![schermafbeelding 2015-03-13 om 15 27 24](https://cloud.githubusercontent.com/assets/1859381/6640108/87c94b78-c995-11e4-8b94-edc1272dfeda.png)

I'll close the issue for now but feel free to let me know if you need further help.

Thanks!
