### ISSUE TITLE
Dynamically adding notifications example grows indefinitely

### ISSUE THREAD

**Issue by frantisekbrabec** [jvandemo/angular-growl-notifications#17]
The "Dynamically adding notifications" example grows the array of notifications indefinitely. Would like to see guidance on when/how to remove the elements from the array in sync with them being hidden from the screen.

**Comment by siulung4073** [comment]
+1

**Comment by jvandemo** [comment]
If you want the object to stay in sync with the notifications in your UI, you can use the `$timeout` service to accomplish this:

```javascript
$scope.add = function(notification){
  var i;

  if(!notification){
    $scope.invalidNotification = true;
    return;
  }

  i = index++;
  $scope.invalidNotification = false;
  $scope.notifications[i] = notification;
  $timeout(function(){
    delete $scope.notifications[i];
  }, timeoutOfYourNotification);
};
```

Can you let me know if that provides you with your desired behavior?

May I ask what the use case is in your application? Then I can get a better idea if this needs better support.

Thanks in advance!!

**Comment by frantisekbrabec** [comment]
The goal would be to have an array to represent individual notifications.
Then in spirit of AngularJS removing a notification on the screen (e.g.,
pressing the 'x' button or by reaching the TTL set within the HTML) would
also remove the corresponding element from the array (i.e., array length
would be previous length -1); correspondingly removing an element from the
array in javascript (e.g., splice) would remove the notification from the
screen.

**Comment by jvandemo** [comment]
@frantisekbrabec @mdash; Okay, I understand your use case.

If you need synchronization of notifications with an array, there may be more appropriate solutions like [angular-toastr](https://github.com/Foxandxss/angular-toastr) or even [angular-cache](https://github.com/jmdobry/angular-cache) if you want to implement your own notifications system.

This library was designed to be completely declarative using a simple directive in the view, which keeps it very light and fast, but also limited in its API, making it a less appropriate choice if you need more programmatic control.

However, you can still accomplish what you need using the code I posted above.

Thanks for your feedback, really helpful and truly appreciated!

**Comment by jvandemo** [comment]
I will close this issue for now, feel free to add comments in case of additional questions or opinions.
