### ISSUE TITLE
Error: after is undefined

### ISSUE THREAD

**Issue by eduardoinnorway** [jvandemo/angular-growl-notifications#20]
When doing this:

        // Move the element to the right location in the DOM
        $animate.move(iElem, growlNotifications.element);

You are actually not specifiying "after" according to the Angular v1.4.4 documentation for $animate, this will give an error.

See: https://docs.angularjs.org/api/ng/service/$animate

**Comment by jvandemo** [comment]
Thank you @eduardoinnorway!

Are you interested in creating a PR for this?

**Comment by jvandemo** [comment]
@eduardoinnorway &mdash; According to the [$animate documentation](https://docs.angularjs.org/api/ng/service/$animate), the `after` argument is optional:

`move(element, parent, [after], [options]);`

Are you experiencing error(s)? If so, can you provide an error log?

Thanks in advance!

**Comment by jvandemo** [comment]
Closed due to lack of response.
