### ISSUE TITLE
growl notification ttl is not getting applied 

### ISSUE THREAD

**Issue by smart987** [jvandemo/angular-growl-notifications#21]
Hi, when I use the following, the message "Loading growl-Notifications" is appearing on the screen.  But then it is remaining their forever, even though I have given ttl=1000, the notification is not disappearing after 1000ms. Could you please let me know, what could be the reason?
<growl-notifications ttl="1000"> Loading growl-Notifications
</growl-notifications>

**Comment by jvandemo** [comment]
Hi, can you provide a link to the page? Or set up a plunk at plnkr.co?

Do you see any errors in the console?

Thanks in advance!

**Comment by smart987** [comment]
I realized cause of issue. Please see the plunker http://plnkr.co/edit/ZZHW0JKumXfdFgjTjVJz?p=preview, if you comment   <growl-notifications></growl-notifications> in the html, ttl given in the directive won't take effect. When I have   <growl-notifications></growl-notifications> above <growl-notification ttl="1000"> </growl-notification >, now the ttl is taking effect. Don't know whether it is bug or it is the way to use this directive.

**Comment by jvandemo** [comment]
Hi,

Thanks for the plunk.

By default the notification is shown for 5 seconds:

```html
<growl-notification>
  <h1>Hi there</h1>
  <p>This is a simple notification that shows when the page loads</p>
</growl-notification>
```

But you can specify a `ttl` to change the duration e.g. 1 second (1000ms):

```html
<growl-notification ttl="1000">
  <h1>Hi there</h1>
  <p>This is a simple notification that shows when the page loads</p>
</growl-notification>
```

Is this not working for you? Or am I misunderstanding your question?

Thanks!

**Comment by smart987** [comment]
Yes that is not working for me. But if I put 

```javascript
<growl-notifications></growl-notifications> 
<growl-notification ttl="1000">
  <h1>Hi there</h1>
  <p>This is a simple notification that shows when the page loads</p>
</growl-notification>
```
ttl is taking effect. But if I take out  `<growl-notifications></growl-notifications>` and give only

```javascript
<growl-notification ttl="1000">
  <h1>Hi there</h1>
  <p>This is a simple notification that shows when the page loads</p>
</growl-notification>
```
That ttl is not taking effect. The message getting remained as it is without disappearing 1000ms.

**Comment by smart987** [comment]
For now my problem is solved because I have `<growl-notifications></growl-notifications> `

**Comment by smart987** [comment]
One small additional information is need, When the notification, disappears after 1000ms, I want to execute a function in the controller. How can I do it?

**Comment by jvandemo** [comment]
@smart987 &mdash; Ah , perfect, yes, you need both directives indeed.

Thanks for the confirmation!

**Comment by jvandemo** [comment]
> One small additional information is need, When the notification, disappears after 1000ms, I want to execute a function in the controller. How can I do it?

You can specify a handler you wish to run when the notification closes:

```html
<growl-notification on-close="doSomething()">
  ...
</growl-notification>
```

Thanks!
