### ISSUE TITLE
on-close not working

### ISSUE THREAD

**Issue by pikkupullo** [jvandemo/angular-growl-notifications#23]
I tried to use the on-close hook, but no luck so far. Neither a function call or just a flag set as in the examples does not work. Has this been updated for angular versions 1.4.0 -> ???

**Comment by pikkupullo** [comment]
Actually solved this, but I don't understand how. The growl-notification element had to be deeper inside the div-structure for the controller to notice it, so this probably has to do something weird with the angular scopes...

**Comment by jvandemo** [comment]
@pikkupullo &mdash; Thanks for the update. Feel free to create a plunk if you want to discuss the actual code. I will close the issue for now. Thanks!
