### ISSUE TITLE
Inline HTML

### ISSUE THREAD

**Issue by Cod3n** [jvandemo/angular-growl-notifications#26]
Inline HTML does not seem to work when I add notification dynamically, is there a config I need to enable?

![image](https://cloud.githubusercontent.com/assets/5764988/14382584/1f172440-fd8f-11e5-9b26-609740bbbe0f.png)

**Comment by jvandemo** [comment]
@Cod3n &mdash; Is it possible to create a plunk with your code? Or post your code here so I can reproduce the behavior? Thanks in advance!

**Comment by Cod3n** [comment]
Hi in my html I have:
```     
<growl-notifications></growl-notifications>
<div ng-repeat="(id, notification) in notifications track by id">
    <growl-notification class="fading {{notification.type}}" ttl={{notification.time}} ng-click="$growlNotification.remove()">
        <div class="growlImg"><img ng-src={{notification.img}} ng-show=notification.img /></div>
        <div class="growlText">{{notification.text}}</div>
    </growl-notification>
</div>
```
notifications is just an array of notification object, which I use to add objects dynamically
```
var notice = { type: "error", text: "This is a <strong>test</strong>", time:5000, img:"" };
$scope.notifications[$scope.notifications.length] = notice;
```

**Comment by jvandemo** [comment]
Thank you for posting your code.

I think you will need the `ngSanitize` module and the `ng-bind-html` directive to make that work:
https://docs.angularjs.org/api/ng/directive/ngBindHtml

It would look something like this:

```html
<div class="growlText" ng-bind-html="notification.text"></div>
```

Can you give that a try and let me know if it works?

Thanks again!

**Comment by Cod3n** [comment]
That did the trick, thank you. Still new to angular...

**Comment by jvandemo** [comment]
@Cod3n &mdash; Awesome, thank you for the confirmation. Welcome to Angular! ;-)
