### ISSUE TITLE
(Proposal) Replace $timeout with $interval (Accommodate Protractor tests)

### ISSUE THREAD

**Issue by sfount** [jvandemo/angular-growl-notifications#28]
As referenced in https://github.com/jvandemo/angular-growl-notifications/pull/27 there are some quirks with Angular's Protractor library waiting on the `$timeout` service. A full discission of this can be found [here](https://github.com/angular/protractor/issues/169). 

**Proposal:**
As mentioned in [this comment](https://github.com/angular/protractor/issues/169#issuecomment-26900746) Protractor does not need to wait on the `$interval` service and so end to end tests perform as standard. 

Replace

``` js
// TTL = 5000
$timeout(function () { }, TTL) //...
```

with

``` js
// only run this interval once - replicating the functionality found in $timeout
var REPEATS  = 1;
$interval(function () {}, TTL, REPEATS) //...
```

I have verified that this change has no breaking implications, however there may be something I've missed. If this is discussed and approved it can be easily implemented.

**Comment by jvandemo** [comment]
@sfount &mdash; This looks like a great way to improve Protractor support indeed.

I will try your alternative in a few scenario's and see if anything breaks.

Thanks again for your great input!

**Comment by jvandemo** [comment]
There is currently a discuss in the AngularJS repository on this:
https://github.com/angular/angular.js/issues/14118

I would suggest to wait for a verdict in that discussion before implementing the `$interval` workaround.

@sfount &mdash; What do you think? Thanks!

**Comment by sfount** [comment]
@jvandemo Looks like there's been no further discussion on https://github.com/angular/angular.js/issues/14118!

https://github.com/jvandemo/angular-growl-notifications/issues/30 updates the repository to fulfill this issue. I have used this component with the $timeout -> $interval update in production and it provides exactly the same behavior.

**Comment by jvandemo** [comment]
@sfount &mdash; Thank you, really appreciated your efforts. I'll have a look at it later this week and merge if possible 👍
