### ISSUE TITLE
on-close function gets called immediately 

### ISSUE THREAD

**Issue by absk82** [jvandemo/angular-growl-notifications#32]
Hi,
I am trying to use angular-growl-notifications for notifications. I am having trouble using on-close handler.

Here is the code snippet, I use to include on-close function : 
`<div><growl-notification ng-if="error" class="alert alert-danger" ttl="50000" on-close="{{onClose()}}" > <strong>{{message}}</strong></growl-notification></d
iv>`

and in the controller : 

   var showErrorMessage = function(msg, $scope) {
            $scope.message=JSON.stringify(msg);
            $scope.error = 1;
            $scope.onClose = function(){
              console.log("Before error = "+$scope.error);
              console.log("onClose called");
              $scope.error = 0;
              console.log("After error = "+$scope.error);
            };

The on-close function gets called immediately multiple times. In addition, it also gets called after the ttl timeout happens. This makes the error flag go to 0 prematurely and not after the ttl timeout has happened, causing the message to not display at all.

Do you think, I am not using it correctly ? In the documentation, I didn't find anything different from what I am doing.

**Comment by jvandemo** [comment]
AngularJS runs your handler immediately because you use an expression.

Don't use an expression (using brackets) when specifying the on-close handler:

```xml
<growl-notification on-open="doSomething()" on-close="doSomethingElse()">
  ...
</growl-notification>
```

Can you let us know if that works for you? Thanks! 👍

**Comment by absk82** [comment]
thanks a ton ! It worked great !! I will close this issue.

**Comment by jvandemo** [comment]
@absk82 &mdash; Awesome, thanks for the confirmation! 👍
