### ISSUE TITLE
unable to download 2.6.0 version

### ISSUE THREAD

**Issue by Dwarkamoye** [jvandemo/angular-growl-notifications#33]
Getting the following while trying 
bower install  angular-growl-notifications :

Additional error details:
Available versions in https://github.com/jvandemo/angular-growl-notifications.git: 2.5.0, 2.4.0, 2.3.0, 2.2.0, 2.1.2, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0

**Comment by jvandemo** [comment]
Thank you for reaching out.

You are totally right—v2.6.0 was not published as a release and thus was not downloadable via bower.

I have published v2.6.0 so the latest version should now be available via Bower.

Thanks again for reporting!
